name: Generate trophy card

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate trophy.svg
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: ${{ github.repository_owner }}
          output: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: dracula
          rows: 1
          margin-w: 8
          margin-h: 8
          no-bg: false
          no-frame: false

      - name: Push trophy.svg to trophy-output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: trophy-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
